server:
  port: 8080

spring:
  application:
    name: franchise-api
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcTransactionManagerAutoConfiguration
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/franchise_db}
      auto-index-creation: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers, prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: "always"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method